[package]
name = "shim-k8s"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "void-shim-k8s"
path = "src/main.rs"

[dependencies]
shim-core = { path = "../shim-core" }
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
clap = { version = "4", features = ["derive"] }
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
uuid = { version = "1", features = ["serde", "v4"] }
